const state={token:localStorage.getItem('formula-token'),user:null,catalog:[]};
const $=s=>document.querySelector(s);const api=async(path,options={})=>{const res=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(state.token?{Authorization:`Bearer ${state.token}`}:{}),...(options.headers||{})}});const data=await res.json();if(!res.ok)throw new Error(data.detail||'请求失败');return data};
function escapeHtml(text){return String(text).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
async function login(event){event.preventDefault();try{const form=new FormData(event.target),data=await api('/api/login',{method:'POST',body:JSON.stringify(Object.fromEntries(form))});state.token=data.token;localStorage.setItem('formula-token',data.token);await initialize()}catch(e){$('#login-panel').insertAdjacentHTML('beforeend',`<p class="error">${escapeHtml(e.message)}</p>`)} }
async function initialize(){try{state.user=await api('/api/me');state.catalog=(await api('/api/catalog')).items;$('#login-panel').hidden=true;$('#workspace').hidden=false;$('#identity').textContent=`${state.user.username}（${state.user.role==='admin'?'管理员':'使用人员'}）`;$('#logout').hidden=false;$('#admin-tab').hidden=state.user.role!=='admin';renderCatalog()}catch(_){localStorage.removeItem('formula-token');state.token=null}}
function renderCatalog(){const list=$('#formula-list');list.innerHTML=state.catalog.map(f=>`<label class="formula"><input type="checkbox" value="${f.id}"> <code>${escapeHtml(f.code)}</code> ${escapeHtml(f.name)}<br><small>${escapeHtml(f.citation)} · 第 ${f.page_number||'-'} 页 · v${f.version}</small></label>`).join('');list.querySelectorAll('input').forEach(input=>input.addEventListener('change',renderParameters));renderParameters()}
function renderParameters(){const selected=[...document.querySelectorAll('#formula-list input:checked')].map(x=>Number(x.value));const selectedFormulas=[];const addFormula=id=>{const formula=state.catalog.find(f=>f.id===id);if(!formula||selectedFormulas.some(f=>f.id===id))return;selectedFormulas.push(formula);formula.dependencies.forEach(code=>{const dependency=state.catalog.find(f=>f.code===code);if(dependency)addFormula(dependency.id)})};selected.forEach(addFormula);const variables=new Map();selectedFormulas.forEach(f=>f.variables.forEach(v=>variables.set(v.code,v)));$('#parameter-list').innerHTML=[...variables.values()].map(v=>`<div class="parameter"><label>${escapeHtml(v.label||v.code)}<input type="number" step="any" name="${escapeHtml(v.code)}" ${v.required!==false?'required':''}></label><span>${escapeHtml(v.unit||'-')}</span></div>`).join('')||'<p class="hint">先选择至少一条公式。</p>'}
$('#login-form').addEventListener('submit',login);$('#logout').onclick=()=>{localStorage.removeItem('formula-token');location.reload()};
document.querySelectorAll('[data-view]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.hidden=x.id!==btn.dataset.view);if(btn.dataset.view==='history')loadHistory();if(btn.dataset.view==='admin')loadAdmin()});
$('#calculation-form').addEventListener('submit',async event=>{event.preventDefault();const ids=[...document.querySelectorAll('#formula-list input:checked')].map(x=>Number(x.value));if(!ids.length)return;const inputs=Object.fromEntries([...new FormData(event.target)].map(([k,v])=>[k,Number(v)]));try{const data=await api('/api/calculate',{method:'POST',body:JSON.stringify({formula_ids:ids,inputs})});$('#result-card').hidden=false;$('#results').innerHTML=Object.entries(data.outputs).map(([code,o])=>`<div class="result"><b>${escapeHtml(code)} · ${escapeHtml(o.name)}</b><div>${Number(o.value).toFixed(2)} ${escapeHtml(o.unit)}</div><small>${escapeHtml(o.citation)} · v${o.version}</small></div>`).join('');$('#trace').textContent=JSON.stringify(data.trace,null,2)}catch(e){$('#result-card').hidden=false;$('#results').innerHTML=`<p class="error">${escapeHtml(e.message)}</p>`;$('#trace').textContent=''}});
async function loadHistory(){const items=(await api('/api/records')).items;$('#history-list').innerHTML=items.length?`<table><tr><th>时间</th><th>结果</th><th>公式版本</th></tr>${items.map(x=>`<tr><td>${escapeHtml(x.created_at)}</td><td><code>${escapeHtml(x.output_json)}</code></td><td>${escapeHtml(x.formula_versions_json)}</td></tr>`).join('')}</table>`:'<p class="hint">暂无计算历史。</p>'}
$('#refresh-history').onclick=loadHistory;
async function loadAdmin(){const items=(await api('/api/admin/catalog')).items;$('#admin-list').innerHTML=items.map(f=>`<div class="formula"><code>${escapeHtml(f.code)}</code> ${escapeHtml(f.name)}<br><small>${escapeHtml(f.status)} · v${f.version} · ${escapeHtml(f.citation)}</small></div>`).join('')}
$('#formula-form').addEventListener('submit',async event=>{event.preventDefault();try{const v=Object.fromEntries(new FormData(event.target));const data=await api('/api/admin/formulas',{method:'POST',body:JSON.stringify({standard_id:1,chapter_id:1,code:v.code,name:v.name,citation:v.citation,page_number:Number(v.page_number),latex:v.latex,variables:JSON.parse(v.variables),rule:JSON.parse(v.rule),example:JSON.parse(v.example)})});$('#draft-result').innerHTML=`<p class="ok">草稿已保存，公式 ID：${data.id}。请通过 API 或后续审核页面执行验算和发布。</p>`;event.target.reset();loadAdmin()}catch(e){$('#draft-result').innerHTML=`<p class="error">${escapeHtml(e.message)}</p>`}});
if(state.token)initialize();
