// Adapted from OpenMEP Suite (MIT, Copyright 2025 Luquman A).
import { forwardRef, type ButtonHTMLAttributes, type HTMLAttributes, type InputHTMLAttributes, type ReactNode, type SelectHTMLAttributes } from 'react';
const cx=(...parts:(string|false|undefined)[])=>parts.filter(Boolean).join(' ');
export function Card({className,...props}:HTMLAttributes<HTMLDivElement>){return <div className={cx('rounded-2xl border border-border bg-surface shadow-card',className)} {...props}/>}
export function Badge({children,tone='muted',className}:{children:ReactNode;tone?:'muted'|'brand'|'success'|'danger'|'warn';className?:string}){const tones={muted:'bg-surface-2 text-muted',brand:'bg-brand/10 text-brand',success:'bg-success/15 text-success',danger:'bg-danger/15 text-danger',warn:'bg-warn/15 text-warn'};return <span className={cx('inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-medium',tones[tone],className)}>{children}</span>}
export const Button=forwardRef<HTMLButtonElement,ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'ghost'|'outline';size?:'sm'|'md'|'lg'}>(function Button({variant='primary',size='md',className,...props},ref){const variants={primary:'bg-brand text-brand-fg hover:brightness-110',outline:'border border-border bg-surface hover:bg-surface-2 text-fg',ghost:'hover:bg-surface-2 text-fg'};const sizes={sm:'h-9 px-3 text-sm',md:'h-11 px-5 text-sm',lg:'h-12 px-7 text-base'};return <button ref={ref} className={cx('inline-flex items-center justify-center gap-2 rounded-xl font-semibold transition disabled:cursor-not-allowed disabled:opacity-60',variants[variant],sizes[size],className)} {...props}/>});
export function Field({label,hint,children}:{label:string;hint?:string;children:ReactNode}){return <label className="flex flex-col gap-1.5"><span className="text-sm font-medium text-fg">{label}</span>{children}{hint&&<span className="text-xs text-muted">{hint}</span>}</label>}
const input='h-11 w-full rounded-xl border border-border bg-surface px-3.5 text-sm text-fg outline-none transition focus:border-brand focus:ring-2 focus:ring-brand/30';
export const Input=forwardRef<HTMLInputElement,InputHTMLAttributes<HTMLInputElement>>(function Input({className,...props},ref){return <input ref={ref} className={cx(input,className)} {...props}/>});
export const Select=forwardRef<HTMLSelectElement,SelectHTMLAttributes<HTMLSelectElement>>(function Select({className,children,...props},ref){return <select ref={ref} className={cx(input,'cursor-pointer',className)} {...props}>{children}</select>});
